#!/bin/bash

# Set the console keyboard layout and font

## The default console keymap is US. Available layouts can be listed with:
# localectl list-keymaps

## To set the keyboard layout, pass its name to loadkeys(1). For example, to set a German keyboard layout:
# loadkeys de-latin1

## Console fonts are located in /usr/share/kbd/consolefonts/ and can likewise be set with setfont(8) omitting the path and file extension. For example, to use one of the largest fonts suitable for HiDPI screens, run:
# setfont ter-132b

# Verify the boot mode

## To verify the boot mode, check the UEFI bitness:
# cat /sys/firmware/efi/fw_platform_size

EXPECTED_FW_PLATFORM_SIZE=64
fw_platform_size=$(cat /sys/firmware/efi/fw_platform_size)

echo "Verifying the boot mode..."

if [[ $fw_platform_size -ne $EXPECTED_FW_PLATFORM_SIZE ]]; then
  echo "Error: Verifying the boot mode failed. The system must be UEFI $EXPECTED_FW_PLATFORM_SIZE-bit, not $fw_platform_size-bit."
  exit 1
fi

# Connect to the internet

## Ensure your network interface is listed and enabled, for example with ip-link(8):
# ip link

## The connection may be verified with ping:
# ping archlinux.org

HOST="archlinux.org"
PING_COUNT=4

echo "Verifying the connection to the internet..."

if ! ping -c $PING_COUNT $HOST > /dev/null; then
  echo "Error: Verifying the connection to the internet failed. Unable to reach $HOST."
  exit 1
fi
