#!/bin/bash

# Installation script with LUKS encryption using LVM for Arch Linux with UEFI 64-bit.
# Copyright (C) 2024  MovieaT33

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set_console_keyboard_layout() {
    local console_keymap="$1"
    loadkeys "$console_keymap"
}

set_font() {
    local font="$1"
    setfont "$font"
}

set_default_font() {
    set_font ""
}

set_large_font() {
    set_font "ter-132b"
}

get_uefi_mode() {
    if [[ -d /sys/firmware/efi ]]; then
        if [[ "$(getconf LONG_BIT)" -eq 64 ]]; then
            echo 64
        else
            echo 32
        fi
    else
        echo "Not in UEFI mode"
        exit 1
    fi
}

verify_boot_mode() {
    local EXPECTED_UEFI_BITNESS=64

    local uefi_mode=$(get_uefi_mode)
    if [[ "$uefi_mode" -ne "$EXPECTED_UEFI_BITNESS" ]]; then
        echo "Unsupported UEFI mode: $uefi_mode-bit. Expected: $EXPECTED_UEFI_BITNESS-bit."
        exit 1
    else
        echo "UEFI mode is supported: $uefi_mode-bit."
    fi
}

verify_internet_connection() {
    local HOST="archlinux.com"

    if ! ping -c 1 archlinux.com > /dev/null; then
        echo "No internet connection"
        exit 1
    fi
}

set_console_keyboard_layout "us"
set_large_font
verify_boot_mode
verify_internet_connection
